production:
  :concurrency: 5
:queues:
  - default
  - mailers
:schedule:
    costs_update_notifier:
      cron: '0 0 9,16 ? * TUE-FRI *'  # Runs twice every week day
      class: UpdateNotifierJob
      args: ['costs']
    general_update_notifier:
      cron: '0 16 * * MON'  # Runs every monday
      class: UpdateNotifierJob
      args: ['general']
    sysadmins_update_notifier:
      cron: '0 9,16 * * TUE-FRI'  # Runs twice every week day
      class: UpdateNotifierJob
      args: ['sysadmins']